listenport: 7070
constring: user:password@tcp(localhost:3306)/databasename
# How many last cronjob logs should be loaded from DB
historylength: 100
# web panel access
webuser: admin
webpass: admin
# mail config
mailfrom: user@example.com
mailpass: mypassworthere
mailhost: gmail.org
mailport: 587
# for url redirecting, set this to root url of web path
host: http://localhost:7070/
# oidc
useoidc: false
clientid: myclient
clientsecret: MYCL1ENTSECRETHERE
issuer: http://localhost:8080/realms/myrealm
oidccookiekey: chng1234chng1234
sessioncookiekey: chng1234chng1234
